import cx_Oracle
from datetime import datetime


class HospitalOracle():
    def __init__(self):
        self.con = cx_Oracle.connect("manager", "hung", "xe")
        self.cur = self.con.cursor()

    def searchPatient(self, PFNAME, PLNAME):
        querySelect = """SELECT PFNAME, PLNAME, PPHONE, EXDATE, EXFEE, EXDIAGNOSIS, EXSECONDEXAMINATIONDATE, TRSTART, TREND, TRRESULT FROM (SELECT PID, PFNAME, PLNAME, PPHONE, EXDATE, EXFEE, EXDIAGNOSIS, EXSECONDEXAMINATIONDATE, NULL AS TRSTART, NULL AS TREND, NULL AS TRRESULT
            FROM HOSPITAL_ADMIN.PATIENT 
            JOIN HOSPITAL_ADMIN.EXAMINATION ON PID=PID_OUT
            UNION
            SELECT PID, PFNAME, PLNAME, PPHONE, NULL AS EXDATE, NULL AS EXFEE, NULL AS EXDIAGNOSIS, NULL AS EXSECONDEXAMINATIONDATE, TRSTART, TREND, TRRESULT
            FROM HOSPITAL_ADMIN.PATIENT
            JOIN HOSPITAL_ADMIN.TREATMENT ON PID=PID_IN)
            WHERE LTRIM(RTRIM(PFNAME))='{}'AND LTRIM(RTRIM(PLNAME))='{}'""".format(PFNAME, PLNAME)
        
        self.cur.execute(querySelect)

        # Return data fetched from cursor
        return self.cur.fetchall()

    def insertIntoPatient(self, PFNAME, PLNAME, PDOB, PGENDER, PPHONE, PADDRESS):
        queryInsert = """BEGIN
                            HOSPITAL_ADMIN.INSERT_INTO_PATIENT('{}','{}',TO_DATE('{}', 'yyyy/mm/dd'),'{}','{}','{}');
                         END;
                            """.format(PFNAME, PLNAME, PDOB, PGENDER, PPHONE, PADDRESS)

        self.cur.execute(queryInsert)
        self.con.commit()
    
    def listPatientTreatedByDoctor(self, DFNAME, DLNAME):
        queryList = """SELECT PID ,PFNAME, PLNAME, PPHONE, PDOB, EXDATE, EXFEE, EXDIAGNOSIS, EXSECONDEXAMINATIONDATE, TRSTART, TREND, TRRESULT FROM (SELECT EID_DOC, PID, PFNAME, PLNAME, PPHONE, PDOB, EXDATE, EXFEE, EXDIAGNOSIS, EXSECONDEXAMINATIONDATE, NULL AS TRSTART, NULL AS TREND, NULL AS TRRESULT
            FROM HOSPITAL_ADMIN.PATIENT 
            JOIN HOSPITAL_ADMIN.EXAMINATION ON PID=PID_OUT
            UNION
            SELECT EID_DOC, PID, PFNAME, PLNAME, PPHONE, PDOB, NULL AS EXDATE, NULL AS EXFEE, NULL AS EXDIAGNOSIS, NULL AS EXSECONDEXAMINATIONDATE, TRSTART, TREND, TRRESULT
            FROM HOSPITAL_ADMIN.PATIENT
            JOIN HOSPITAL_ADMIN.TREATMENT ON PID=PID_IN)
            WHERE EID_DOC IN (SELECT EID FROM EMPLOYEE WHERE LTRIM(RTRIM(EFNAME))='{}' AND LTRIM(RTRIM(ELNAME))='{}')
            """.format(DFNAME, DLNAME)

        self.cur.execute(queryList)

        return self.cur.fetchall()

    def makeAReport(self, PFNAME, PLNAME):
        queryReport = """SELECT * FROM (SELECT P.PID, E.EXID, NULL AS TRID, COALESCE(SUM(MPRICE),0) AS TOTALMPRICE, EXFEE AS TOTALEXFEE, NULL AS TOTALPFEE, SUM(MPRICE + EXFEE) AS OUTPAYMENT, NULL AS INPAYMENT FROM HOSPITAL_ADMIN.PATIENT P
JOIN HOSPITAL_ADMIN.OUTPATIENT OP ON PID_OUT=PID
JOIN HOSPITAL_ADMIN.EXAMINATION E ON E.PID_OUT=OP.PID_OUT 
LEFT JOIN HOSPITAL_ADMIN.USES_EXAM UE ON (UE.PID_OUT=E.PID_OUT AND E.EID_DOC=UE.EID_DOC) LEFT JOIN HOSPITAL_ADMIN.MEDICATION M ON UE.MID=M.MID
GROUP BY P.PID, E.EXID, E.EXFEE
UNION
SELECT P.PID, NULL AS EXID, T.TRID, COALESCE(SUM(MPRICE),0) AS TOTALMPRICE, NULL AS TOTALEXFEE, PFEE AS TOTALPFEE, NULL AS OUTPAYMENT, SUM(MPRICE + PFEE) AS INPAYMENT FROM HOSPITAL_ADMIN.PATIENT P
JOIN HOSPITAL_ADMIN.INPATIENT IP ON PID_IN=PID
JOIN HOSPITAL_ADMIN.TREATMENT T ON T.PID_IN=IP.PID_IN 
LEFT JOIN HOSPITAL_ADMIN.USES_TREAT UT ON (UT.PID_IN=T.PID_IN AND T.EID_DOC=UT.EID_DOC) LEFT JOIN HOSPITAL_ADMIN.MEDICATION M ON UT.MID=M.MID
GROUP BY P.PID, T.TRID, PFEE)
WHERE PID IN (SELECT PID FROM HOSPITAL_ADMIN.PATIENT WHERE LTRIM(RTRIM(PFNAME))='{}' AND LTRIM(RTRIM(PLNAME))='{}')""".format(PFNAME, PLNAME)

        self.cur.execute(queryReport)

        return self.cur.fetchall()
                